<?php
if ( ! defined( 'ABSPATH' ) ) exit;

/**
 * FormPilot Pro launch/onboarding layer.
 * Provides contextual guidance for every product screen without changing the
 * underlying scheduling/form/payment subsystems.
 */

function fp_help_pages() {
    return [
        'ssb-dashboard' => [
            'title' => 'Start here',
            'summary' => 'Finish the launch checklist, connect the services you use, then publish your first event or form.',
            'steps' => ['Connect at least one calendar or meeting provider.', 'Create an event type and confirm its availability.', 'Open the public booking link in a private browser and complete a test booking.'],
            'example' => 'Typical first setup: Google Calendar + 30-minute Consultation + Google Meet + confirmation/reminder workflow.',
        ],
        'ssb-forms' => [
            'title' => 'Build a form',
            'summary' => 'Use Forms for leads, intake, surveys and any workflow that does not need a time slot.',
            'steps' => ['Create a form and add only the fields you need.', 'Set confirmation behavior and integrations.', 'Embed the generated shortcode on a page and submit one test entry.'],
            'example' => 'Lead form: Name, Email, Company, What can we help with? → email notification + CRM sync.',
        ],
        'ssb-bookings' => [
            'title' => 'Legacy booking records',
            'summary' => 'This screen contains bookings created by the original booking flow. New event-type bookings are managed under Scheduling Bookings.',
            'steps' => ['Use Scheduling Bookings for event-type appointments.', 'Use this screen only for records generated by the original booking widget.', 'Before launch, verify which booking experience is published on your site.'],
            'example' => 'If you publish a FormPilot Event Type link, manage those appointments in Scheduling Bookings.',
        ],
        'fp-scheduling' => [
            'title' => 'Create an event type',
            'summary' => 'An event type defines what a visitor can book: duration, hosts, capacity, location and weekly availability.',
            'steps' => ['Choose One-on-one for a single host or Group/Collective/Round Robin for multi-person scheduling.', 'Set the location provider and host pool.', 'Add weekly availability, save, then open the generated public link and test it.'],
            'example' => '30-minute Consultation · One-on-one · Google Meet · Mon–Fri 09:00–17:00 · 15-minute buffer.',
        ],
        'fp-availability' => [
            'title' => 'Control when people can book',
            'summary' => 'Availability is evaluated together with existing FormPilot bookings and connected-calendar conflicts.',
            'steps' => ['Edit the event type whose hours you want to change.', 'Add the weekly windows for that event.', 'Connect Google Calendar if external calendar conflicts must block slots.'],
            'example' => 'Mon–Thu 09:00–12:00 and 14:00–17:00; Friday 09:00–13:00; weekends closed.',
        ],
        'fp-bookings' => [
            'title' => 'Manage appointments',
            'summary' => 'Review upcoming bookings, payment state, meeting location and customer details from one place.',
            'steps' => ['Confirm the event, attendee and start time.', 'Use the management link for cancellation or rescheduling when needed.', 'Check payment/invoice state for paid event types.'],
            'example' => 'A paid Strategy Call should show the attendee, confirmed time, provider meeting URL and paid invoice status.',
        ],
        'fp-teams' => [
            'title' => 'Build host pools',
            'summary' => 'Teams let Round Robin and Collective event types use multiple WordPress users as hosts.',
            'steps' => ['Create a team.', 'Add the WordPress user IDs that can host meetings.', 'Use those hosts when configuring a team event type.'],
            'example' => 'Sales Team: user 2, user 5, user 8 → Round Robin Demo event distributes eligible meetings across the pool.',
        ],
        'fp-routing' => [
            'title' => 'Route visitors to the right event',
            'summary' => 'Routing asks qualifying questions and sends the visitor to the first matching event rule, with a default fallback.',
            'steps' => ['Create clear questions with short answer options.', 'Map each rule to an existing event type.', 'Always set a sensible default event and test every route.'],
            'example' => 'Question: Company size → “1–10” routes to Starter Consultation; “11–50” routes to Growth Demo.',
        ],
        'fp-workflows' => [
            'title' => 'Automate reminders and follow-up',
            'summary' => 'Workflows send queued email/webhook actions when booking events occur, including delayed reminders and follow-ups.',
            'steps' => ['Choose the booking trigger.', 'Add the action and delay.', 'Create a test booking and confirm the queued action runs as expected.'],
            'example' => 'Booking created → confirmation immediately; reminder 24 hours before; follow-up email 60 minutes after the meeting.',
        ],
        'fp-polls' => [
            'title' => 'Find a time with a group',
            'summary' => 'Meeting Polls let invitees vote on proposed time options before you commit to a final meeting.',
            'steps' => ['Create the poll and add several realistic time choices.', 'Share the public poll link.', 'Review votes and use the strongest option to create the final meeting.'],
            'example' => 'Project kickoff poll with Tuesday 10:00, Tuesday 14:00 and Wednesday 11:00.',
        ],
        'fp-links' => [
            'title' => 'Create controlled booking links',
            'summary' => 'Single-use links are useful when a normal public event URL should not be reusable indefinitely.',
            'steps' => ['Choose the event type.', 'Set the maximum uses and expiration.', 'Send the generated URL directly to the intended recipient.'],
            'example' => 'Candidate interview link: 1 use, expires in 7 days.',
        ],
        'fp-contacts' => [
            'title' => 'Use your scheduling contact history',
            'summary' => 'Contacts are created or updated automatically from bookings and can also be synchronized to enabled CRM integrations.',
            'steps' => ['Use email as the primary customer identifier.', 'Verify new test bookings create/update a contact.', 'Enable HubSpot or Salesforce if the contact must also be sent to your CRM.'],
            'example' => 'A returning customer books twice with the same email; FormPilot updates the existing contact instead of creating a duplicate.',
        ],
        'fp-analytics' => [
            'title' => 'Read scheduling performance',
            'summary' => 'Analytics summarizes bookings and contact activity. Use test traffic before launch so you understand the metrics.',
            'steps' => ['Review total and upcoming bookings.', 'Compare activity after publishing new event links.', 'Use your CRM/analytics stack for broader marketing attribution when needed.'],
            'example' => 'Track whether a new Demo event increases confirmed bookings after you add it to a campaign landing page.',
        ],
        'fp-integrations' => [
            'title' => 'Connect providers safely',
            'summary' => 'Configure credentials here, save them, then use Test connection before assigning that provider to live event types.',
            'steps' => ['Create the required app/account credentials with the provider.', 'Paste only the required values into FormPilot and save.', 'Run Test connection, then make one real test booking.'],
            'example' => 'For Zoom: configure Server-to-Server OAuth → save Account ID, Client ID, Client Secret and host email → Test connection → use Zoom as an Event Type location.',
            'integrations' => true,
        ],
        'fp-branding' => [
            'title' => 'Match the scheduler to your brand',
            'summary' => 'Branding controls the public scheduling experience rather than the WordPress admin.',
            'steps' => ['Upload your logo and choose an accessible accent color.', 'Set background/radius values.', 'Preview at least one event page on desktop and mobile before launch.'],
            'example' => 'Use your company logo, brand accent color and a clean white background; avoid custom CSS unless you need a specific override.',
        ],
        'fp-invoices' => [
            'title' => 'Review paid booking invoices',
            'summary' => 'Invoices are generated for paid scheduling transactions and can be viewed through their public tokenized URL.',
            'steps' => ['Create a paid event type.', 'Complete a Stripe test-mode booking.', 'Confirm the invoice amount, currency, customer and status are correct.'],
            'example' => 'USD 99 Strategy Session → successful Stripe payment → invoice created and attached to the booking.',
        ],
        'fp-api' => [
            'title' => 'Send booking events to other systems',
            'summary' => 'Webhooks provide event delivery; the API provides programmatic access. Keep secrets server-side.',
            'steps' => ['Add a HTTPS webhook endpoint and secret.', 'Trigger a test booking and verify the HMAC signature in your receiver.', 'Use API Keys for authenticated external API clients, not public browser code.'],
            'example' => 'booking.created webhook → your CRM/middleware endpoint → verify X-FormPilot-Signature before processing.',
        ],
        'fp-api-keys' => [
            'title' => 'Create server-to-server API credentials',
            'summary' => 'API keys are for trusted applications. Treat every key like a password.',
            'steps' => ['Create a key for one integration/service.', 'Store it in that service’s secret manager.', 'Rotate/revoke a key when the integration is retired or exposed.'],
            'example' => 'Create “Internal CRM Sync” as a dedicated key instead of reusing one key for several applications.',
        ],
        'fp-marketplace' => [
            'title' => 'Start from a proven template',
            'summary' => 'Marketplace templates create editable event types; review every imported setting before sharing the link.',
            'steps' => ['Choose the closest use-case template.', 'Import it and edit title, hosts, location and availability.', 'Open the public link and complete a test booking.'],
            'example' => 'Import “30-minute Consultation”, switch location to Zoom and adjust availability to your local working hours.',
        ],
        'ssb-payment-buttons' => [
            'title' => 'Create payment links/buttons',
            'summary' => 'Use payment buttons for standalone payments. Use paid Event Types when payment must be tied directly to a scheduled appointment.',
            'steps' => ['Connect Stripe first.', 'Create a test-mode payment button.', 'Run a complete test payment before enabling live mode.'],
            'example' => 'Standalone deposit button for USD 50; for a USD 50 paid consultation, configure the price on the Event Type instead.',
        ],
        'ssb-settings' => [
            'title' => 'Configure global defaults',
            'summary' => 'Settings contain shared behavior such as email, Google Calendar and Stripe configuration.',
            'steps' => ['Review sender/email settings.', 'Connect Google Calendar and Stripe if you use them.', 'Send a test email and complete provider connection tests before launch.'],
            'example' => 'Use a domain-based From address, connect the primary work calendar, and leave Stripe in test mode until checkout is verified.',
        ],
        'ssb-license' => [
            'title' => 'Keep premium services authorized',
            'summary' => 'The license controls premium feature entitlement and updates for this domain.',
            'steps' => ['Activate the license on the production domain.', 'Confirm the status reads active.', 'Use Check License Now after changing plan/domain/license state.'],
            'example' => 'Production site active on the licensed domain; staging should use an activation allowed by your plan.',
        ],
    ];
}

function fp_help_integration_guides() {
    $settings = admin_url('admin.php?page=ssb-settings');
    $a = static function($url, $label) {
        return '<a href="'.esc_url($url).'" target="_blank" rel="noopener noreferrer">'.esc_html($label).'</a>';
    };
    return [
        'google' => [
            'name' => 'Google Calendar + Google Meet',
            'purpose' => 'Block busy times, create calendar events and optionally add Google Meet links.',
            'steps' => [
                'Go to '.$a('https://console.cloud.google.com/','Google Cloud Console').' → Create or select a project.',
                'Enable the '.$a('https://console.cloud.google.com/apis/library/calendar-json.googleapis.com','Google Calendar API').' (APIs & Services → Library).',
                'Open '.$a('https://console.cloud.google.com/apis/credentials/consent','OAuth consent screen').' → choose External if appropriate → enter the app name/email → add your Google account as a Test User while the app is in testing.',
                'Create OAuth credentials from '.$a('https://console.cloud.google.com/apis/credentials','APIs & Services → Credentials').' → Create Credentials → OAuth client ID → Web application.',
                'Add this exact Authorized Redirect URI to the OAuth client: <code>'.esc_html(ssb_google_redirect_uri()).'</code>',
                'Copy the Client ID and Client Secret into FormPilot, save, then click Connect Google Calendar. Select the calendar and enable Google Meet if required.',
            ],
            'test' => 'Create a private test Event Type using Google Meet, book it, and confirm the event appears on the connected calendar without overlapping a busy period.',
            'url' => $settings.'&tab=google',
        ],
        'stripe' => [
            'name' => 'Stripe',
            'purpose' => 'Collect card payments for paid event types and payment buttons.',
            'steps' => [
                'Open your '.$a('https://dashboard.stripe.com/','Stripe Dashboard').' and keep Test mode enabled while configuring FormPilot.',
                'Open '.$a('https://dashboard.stripe.com/test/apikeys','Stripe API keys').' → copy the Publishable key and Secret key.',
                'Paste both keys into FormPilot Stripe settings and keep Test mode enabled.',
                'Create a paid Event Type with an amount/currency and complete a test checkout using a '.$a('https://docs.stripe.com/testing','Stripe test card').' .',
                'After the complete test passes, replace test keys with live keys and disable Test mode.',
            ],
            'test' => 'Book a paid event in Stripe test mode and verify FormPilot creates the booking only after the PaymentIntent succeeds, then check the generated invoice under FormPilot Pro → Invoices.',
            'url' => $settings.'&tab=payment',
        ],
        'zoom' => [
            'name' => 'Zoom',
            'purpose' => 'Automatically create a Zoom meeting when a Zoom event type is booked.',
            'steps' => [
                'Open the '.$a('https://marketplace.zoom.us/','Zoom App Marketplace').' and sign in to the Zoom account that will host meetings.',
                'Create a Server-to-Server OAuth app, activate it, and configure the meeting permissions required to create meetings for the selected host.',
                'Copy the Account ID, Client ID and Client Secret from the app credentials page.',
                'Enter those values plus the Zoom host email in FormPilot → Zoom, then enable Zoom.',
                'Save and click Test connection before assigning Zoom as an Event Type location.',
                'If you need provider-side guidance, use the '.$a('https://developers.zoom.us/docs/integrations/','Zoom developer integration documentation').' for the current OAuth setup.',
            ],
            'test' => 'Book a Zoom Event Type and confirm FormPilot creates a new Zoom meeting and stores its join URL on the booking.',
        ],
        'teams' => [
            'name' => 'Microsoft Teams',
            'purpose' => 'Create Microsoft Teams online meetings through Microsoft Graph.',
            'steps' => [
                'Open the '.$a('https://entra.microsoft.com/','Microsoft Entra admin center').' and register an application under Entra ID → App registrations.',
                'Create a client secret and copy the Tenant ID, Application (Client) ID and Client Secret.',
                'Open the app’s API permissions → Add a permission → Microsoft Graph → Application permissions. For FormPilot online meetings, Microsoft documents '.$a('https://learn.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-1.0','OnlineMeetings.ReadWrite.All').' for application access.',
                'If your tenant requires it, follow Microsoft’s '.$a('https://learn.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy','application access policy').' guidance and grant the app access to the organizer user.',
                'Enter Tenant ID, Client ID, Client Secret and the organizer Microsoft 365 user ID/email in FormPilot → Microsoft Teams.',
                'Save, run Test connection, complete Microsoft admin consent/access-policy steps required by your tenant, then assign Teams to an Event Type.',
            ],
            'test' => 'Book a Teams Event Type and confirm the booking receives a new Teams meeting URL.',
        ],
        'hubspot' => [
            'name' => 'HubSpot',
            'purpose' => 'Create or update CRM contacts when bookings are created.',
            'steps' => [
                'Open the '.$a('https://developers.hubspot.com/','HubSpot Developer portal').' and sign in to the HubSpot account that will receive FormPilot contacts.',
                'Create a Private App. HubSpot’s current developer documentation explains the '.$a('https://developers.hubspot.com/docs/guides/apps/private-apps/overview','Private App setup').' and access-token flow.',
                'Grant the CRM contact scopes required to read/write contacts, then create the app and copy its access token.',
                'Paste the token into FormPilot → HubSpot, enable HubSpot and save.',
                'Run Test connection, then create a booking with a new test email address.',
            ],
            'test' => 'Confirm the booking email appears as a HubSpot contact and that a repeat booking updates the same contact instead of creating a duplicate.',
        ],
        'salesforce' => [
            'name' => 'Salesforce',
            'purpose' => 'Synchronize booking contacts to Salesforce.',
            'steps' => [
                'Sign in to your '.$a('https://login.salesforce.com/','Salesforce org').' and open Setup.',
                'For a new integration, review Salesforce’s current '.$a('https://help.salesforce.com/s/articleView?id=platform.ev_relay_create_connected_app.htm&language=en_US','OAuth / Connected App guidance').' and the newer External Client App approach where available. Salesforce notes that new Connected App creation is restricted in Spring ’26.',
                'Obtain an OAuth access token with permission to work with the required contact records. FormPilot currently accepts the access token directly rather than storing a Salesforce username/password.',
                'Copy your Salesforce instance URL (for example your My Domain URL) and the access token, then enter both in FormPilot → Salesforce.',
                'Run Test connection, then make a booking using a test contact.',
            ],
            'test' => 'Confirm the contact is synchronized to Salesforce. If the OAuth token expires, renew the token and test the connection again.',
        ],
    ];
}

function fp_help_current_page() {
    if ( ! is_admin() || empty($_GET['page']) ) return '';
    return sanitize_key(wp_unslash($_GET['page']));
}

add_action('admin_notices', 'fp_help_context_notice', 2);
function fp_help_context_notice() {
    if ( ! current_user_can('manage_options') ) return;
    $page = fp_help_current_page();
    if ( ! $page || $page === 'fp-help' ) return;
    $catalog = fp_help_pages();
    if ( empty($catalog[$page]) ) return;
    $g = $catalog[$page];
    echo '<div class="fp-context-help">';
    echo '<details'.($page==='fp-integrations'?' open':'').'>';
    echo '<summary><span class="dashicons dashicons-lightbulb"></span><strong>'.esc_html($g['title']).'</strong><span class="fp-help-summary-copy">'.esc_html($g['summary']).'</span><span class="fp-help-open">Guide</span></summary>';
    echo '<div class="fp-help-body"><div class="fp-help-columns"><div><h3>Quick start</h3><ol>';
    foreach($g['steps'] as $s) echo '<li>'.esc_html($s).'</li>';
    echo '</ol></div><div class="fp-example-box"><span>EXAMPLE</span><p>'.esc_html($g['example']).'</p></div></div>';
    if ( ! empty($g['integrations']) ) fp_help_render_integrations();
    echo '<p class="fp-help-more"><a href="'.esc_url(admin_url('admin.php?page=fp-help')).'">Open the complete FormPilot Launch Guide →</a></p>';
    echo '</div></details></div>';
}

function fp_help_render_integrations() {
    $guides = fp_help_integration_guides();
    echo '<div class="fp-integration-howto"><h3>Provider setup guides</h3><p>Use the guide for the service you want to connect. Save credentials first, run <strong>Test connection</strong>, then complete an end-to-end booking test.</p><div class="fp-guide-grid">';
    foreach($guides as $key=>$g){
        echo '<details class="fp-guide-card"><summary><span class="fp-guide-mark">'.esc_html(strtoupper(substr($g['name'],0,1))).'</span><span><strong>'.esc_html($g['name']).'</strong><small>'.esc_html($g['purpose']).'</small></span><span class="dashicons dashicons-arrow-down-alt2"></span></summary><div class="fp-guide-content"><ol>';
        foreach($g['steps'] as $s) echo '<li>'.esc_html($s).'</li>';
        echo '</ol><div class="fp-test-callout"><strong>Verify it:</strong> '.esc_html($g['test']).'</div>';
        $provider_urls=['google'=>admin_url('admin.php?page=fp-integration-google'),'stripe'=>admin_url('admin.php?page=fp-integration-stripe'),'zoom'=>admin_url('admin.php?page=fp-integration-zoom'),'teams'=>admin_url('admin.php?page=fp-integration-teams'),'hubspot'=>admin_url('admin.php?page=fp-integration-hubspot'),'salesforce'=>admin_url('admin.php?page=fp-integration-salesforce')]; $guide_url=$provider_urls[$key]??($g['url']??''); if($guide_url) echo '<p><a class="button button-secondary" href="'.esc_url($guide_url).'">Open '.esc_html($g['name']).' settings</a></p>';
        echo '</div></details>';
    }
    echo '</div></div>';
}

function fp_help_launch_status() {
    global $wpdb;
    $t = function_exists('fp_sched_tables') ? fp_sched_tables() : [];
    $uid = get_current_user_id();
    $events = !empty($t['events']) ? (int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$t['events']} WHERE user_id=%d AND active=1",$uid)) : 0;
    $availability = (!empty($t['availability']) && $events) ? (int)$wpdb->get_var("SELECT COUNT(*) FROM {$t['availability']}") : 0;
    $workflows = !empty($t['workflows']) ? (int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$t['workflows']} WHERE user_id=%d",$uid)) : 0;
    $license = function_exists('ssb_license_status') ? ssb_license_status() : ['active'=>false];
    $integrated = (function_exists('ssb_google_is_connected') && ssb_google_is_connected()) || !empty(get_option('ssb_stripe_secret_key'));
    if(function_exists('fp_adv_integration')) foreach(['zoom','teams','hubspot','salesforce'] as $p) if(fp_adv_integration($uid,$p)){$integrated=true;break;}
    $brand = get_option('fp_sched_branding',[]);
    return [
        ['done'=>!empty($license['active']),'label'=>'License active','link'=>admin_url('admin.php?page=ssb-license')],
        ['done'=>$integrated,'label'=>'At least one provider connected','link'=>admin_url('admin.php?page=fp-integrations')],
        ['done'=>$events>0,'label'=>'At least one active event type','link'=>admin_url('admin.php?page=fp-scheduling')],
        ['done'=>$availability>0,'label'=>'Availability configured','link'=>admin_url('admin.php?page=fp-availability')],
        ['done'=>$workflows>0,'label'=>'Confirmation/reminder workflow reviewed','link'=>admin_url('admin.php?page=fp-workflows')],
        ['done'=>!empty($brand['logo'])||!empty($brand['accent']),'label'=>'Public scheduler branding reviewed','link'=>admin_url('admin.php?page=fp-branding')],
    ];
}

function fp_help_page() {
    if(!current_user_can('manage_options')) return;
    $status=fp_help_launch_status(); $done=0; foreach($status as $x) if($x['done']) $done++; $pct=(int)round(($done/max(1,count($status)))*100);
    echo '<div class="wrap fp-help-page"><div class="fp-help-hero"><div><div class="fp-eyebrow">FORMPILOT PRO</div><h1>Launch Guide & Help Center</h1><p>A practical setup path, real examples, and provider-specific integration instructions for your team.</p></div><div class="fp-launch-score"><strong>'.$pct.'%</strong><span>launch checklist</span></div></div>';
    echo '<section class="fp-help-section"><div class="fp-section-head"><div><h2>Launch checklist</h2><p>Complete these before sending customers to a FormPilot page.</p></div></div><div class="fp-check-grid">';
    foreach($status as $x)echo '<a class="fp-check-item '.($x['done']?'is-done':'').'" href="'.esc_url($x['link']).'"><span class="dashicons '.($x['done']?'dashicons-yes-alt':'dashicons-marker').'"></span><span>'.esc_html($x['label']).'</span><strong>'.($x['done']?'Done':'Review').' →</strong></a>';
    echo '</div></section>';
    echo '<section class="fp-help-section"><div class="fp-section-head"><div><h2>Integration setup</h2><p>Step-by-step instructions for every live provider supported by the scheduler.</p></div><a class="button button-primary" href="'.esc_url(admin_url('admin.php?page=fp-integrations')).'">Open integrations</a></div>';
    fp_help_render_integrations(); echo '</section>';
    echo '<section class="fp-help-section"><div class="fp-section-head"><div><h2>Feature playbook</h2><p>Every FormPilot screen includes this same contextual help at the top. Use these examples as starting points, not rigid defaults.</p></div></div><div class="fp-playbook-grid">';
    foreach(fp_help_pages() as $slug=>$g){if($slug==='ssb-dashboard'||$slug==='fp-integrations')continue;echo '<a class="fp-playbook-card" href="'.esc_url(admin_url('admin.php?page='.$slug)).'"><span>'.esc_html($g['title']).'</span><p>'.esc_html($g['example']).'</p><strong>Open feature →</strong></a>';}
    echo '</div></section>';
    echo '<section class="fp-help-section fp-prelaunch"><h2>Recommended pre-launch test</h2><ol><li>Use provider test/sandbox mode where available.</li><li>Create one event for every event type you plan to sell or publish.</li><li>Book from an incognito/private browser as a customer.</li><li>Check calendar conflict handling, meeting URL, confirmation/reminder, CRM sync and payment/invoice behavior.</li><li>Cancel and reschedule a test booking.</li><li>Repeat on a mobile device.</li><li>Only then switch payment/provider credentials to production where applicable.</li></ol></section></div>';
}
