<?php
if (!defined('ABSPATH')) exit;

function ssb_template_library(){
    $t=[];
    $add=function($id,$cat,$name,$desc,$fields)use(&$t){$t[$id]=['id'=>$id,'category'=>$cat,'name'=>$name,'description'=>$desc,'fields'=>$fields];};
    $text=function($id,$label,$type='text',$required=true,$options=[]){return ['id'=>$id,'type'=>$type,'label'=>$label,'placeholder'=>'','required'=>$required,'options'=>$options,'width'=>'full','help_text'=>''];};
    $add('contact-us','Lead Capture','Contact Us','Simple website contact form.',[['id'=>'name','type'=>'text','label'=>'Name','required'=>true],['id'=>'email','type'=>'email','label'=>'Email','required'=>true],['id'=>'message','type'=>'textarea','label'=>'Message','required'=>true]]);
    $add('lead-capture','Lead Capture','Lead Capture','Capture prospects with qualification.',[['id'=>'name','type'=>'text','label'=>'Full name','required'=>true],['id'=>'email','type'=>'email','label'=>'Work email','required'=>true],['id'=>'company','type'=>'text','label'=>'Company','required'=>false],['id'=>'interest','type'=>'select','label'=>'What are you interested in?','required'=>true,'options'=>['Demo','Pricing','Consulting','Support']]]);
    $add('sales-demo','Sales','Sales Demo Request','Book-ready demo request form.',[['id'=>'name','type'=>'text','label'=>'Name','required'=>true],['id'=>'email','type'=>'email','label'=>'Work email','required'=>true],['id'=>'company','type'=>'text','label'=>'Company','required'=>true],['id'=>'size','type'=>'select','label'=>'Company size','required'=>true,'options'=>['1-10','11-50','51-200','201-1000','1000+']]]);
    $add('discovery-call','Sales','Discovery Call','Pre-qualify a discovery call.',[['id'=>'name','type'=>'text','label'=>'Name','required'=>true],['id'=>'email','type'=>'email','label'=>'Email','required'=>true],['id'=>'goal','type'=>'textarea','label'=>'What would you like to accomplish?','required'=>true],['id'=>'budget','type'=>'select','label'=>'Budget range','required'=>false,'options'=>['Under $1k','$1k-$5k','$5k-$10k','$10k+']]]);
    $add('consultation','Consulting','Consultation Request','Professional consultation intake.',[['id'=>'name','type'=>'text','label'=>'Name','required'=>true],['id'=>'email','type'=>'email','label'=>'Email','required'=>true],['id'=>'topic','type'=>'select','label'=>'Consultation topic','required'=>true,'options'=>['Strategy','Operations','Marketing','Technology','Other']],['id'=>'details','type'=>'textarea','label'=>'Tell us more','required'=>true]]);
    $add('coaching-call','Coaching','Coaching Session','Client intake for a coaching session.',[['id'=>'name','type'=>'text','label'=>'Name','required'=>true],['id'=>'email','type'=>'email','label'=>'Email','required'=>true],['id'=>'goal','type'=>'textarea','label'=>'Your goal for this session','required'=>true],['id'=>'experience','type'=>'select','label'=>'Experience level','required'=>false,'options'=>['Beginner','Intermediate','Advanced']]]);
    $add('interview','Hiring','Candidate Interview','Interview scheduling intake.',[['id'=>'name','type'=>'text','label'=>'Candidate name','required'=>true],['id'=>'email','type'=>'email','label'=>'Email','required'=>true],['id'=>'role','type'=>'text','label'=>'Role','required'=>true],['id'=>'notes','type'=>'textarea','label'=>'Notes','required'=>false]]);
    $add('job-application','Hiring','Job Application','Application intake.',[['id'=>'name','type'=>'text','label'=>'Full name','required'=>true],['id'=>'email','type'=>'email','label'=>'Email','required'=>true],['id'=>'phone','type'=>'tel','label'=>'Phone','required'=>true],['id'=>'role','type'=>'select','label'=>'Role','required'=>true,'options'=>['Sales','Engineering','Marketing','Operations','Other']],['id'=>'resume','type'=>'file','label'=>'Resume','required'=>false]]);
    $add('customer-support','Support','Customer Support','Support request triage.',[['id'=>'name','type'=>'text','label'=>'Name','required'=>true],['id'=>'email','type'=>'email','label'=>'Email','required'=>true],['id'=>'priority','type'=>'select','label'=>'Priority','required'=>true,'options'=>['Low','Normal','High','Urgent']],['id'=>'message','type'=>'textarea','label'=>'How can we help?','required'=>true]]);
    $add('product-feedback','Feedback','Product Feedback','Collect product feedback.',[['id'=>'name','type'=>'text','label'=>'Name','required'=>false],['id'=>'email','type'=>'email','label'=>'Email','required'=>false],['id'=>'rating','type'=>'rating','label'=>'Overall rating','required'=>true],['id'=>'feedback','type'=>'textarea','label'=>'Feedback','required'=>true]]);
    $add('testimonial','Marketing','Testimonial Request','Request customer testimonials.',[['id'=>'name','type'=>'text','label'=>'Name','required'=>true],['id'=>'email','type'=>'email','label'=>'Email','required'=>true],['id'=>'testimonial','type'=>'textarea','label'=>'Your testimonial','required'=>true],['id'=>'permission','type'=>'checkbox','label'=>'You may publish my testimonial','required'=>true]]);
    $add('event-rsvp','Events','Event RSVP','Collect event registrations.',[['id'=>'name','type'=>'text','label'=>'Name','required'=>true],['id'=>'email','type'=>'email','label'=>'Email','required'=>true],['id'=>'attendance','type'=>'radio','label'=>'Attendance','required'=>true,'options'=>['In person','Virtual']],['id'=>'guests','type'=>'number','label'=>'Number of guests','required'=>false]]);
    $add('webinar-registration','Events','Webinar Registration','Webinar signup.',[['id'=>'name','type'=>'text','label'=>'Name','required'=>true],['id'=>'email','type'=>'email','label'=>'Email','required'=>true],['id'=>'company','type'=>'text','label'=>'Company','required'=>false],['id'=>'questions','type'=>'textarea','label'=>'Questions for the speaker','required'=>false]]);
    $add('workshop-booking','Events','Workshop Registration','Workshop intake.',[['id'=>'name','type'=>'text','label'=>'Name','required'=>true],['id'=>'email','type'=>'email','label'=>'Email','required'=>true],['id'=>'session','type'=>'select','label'=>'Session','required'=>true,'options'=>['Morning','Afternoon','Evening']],['id'=>'diet','type'=>'text','label'=>'Dietary requirements','required'=>false]]);
    $add('medical-intake','Professional','Appointment Intake','General professional appointment intake; customize for your regulated workflow.',[['id'=>'name','type'=>'text','label'=>'Full name','required'=>true],['id'=>'email','type'=>'email','label'=>'Email','required'=>true],['id'=>'phone','type'=>'tel','label'=>'Phone','required'=>true],['id'=>'reason','type'=>'textarea','label'=>'Reason for appointment','required'=>true]]);
    $add('real-estate','Real Estate','Property Consultation','Real-estate lead intake.',[['id'=>'name','type'=>'text','label'=>'Name','required'=>true],['id'=>'email','type'=>'email','label'=>'Email','required'=>true],['id'=>'type','type'=>'select','label'=>'Property type','required'=>true,'options'=>['Buy','Sell','Rent','Invest']],['id'=>'location','type'=>'text','label'=>'Preferred area','required'=>true]]);
    $add('legal-consult','Professional','Legal Consultation Request','Client intake for a consultation.',[['id'=>'name','type'=>'text','label'=>'Name','required'=>true],['id'=>'email','type'=>'email','label'=>'Email','required'=>true],['id'=>'matter','type'=>'select','label'=>'Matter type','required'=>true,'options'=>['Business','Family','Property','Employment','Other']],['id'=>'summary','type'=>'textarea','label'=>'Brief summary','required'=>true]]);
    $add('financial-consult','Professional','Financial Consultation','Financial services lead intake.',[['id'=>'name','type'=>'text','label'=>'Name','required'=>true],['id'=>'email','type'=>'email','label'=>'Email','required'=>true],['id'=>'service','type'=>'select','label'=>'Service','required'=>true,'options'=>['Planning','Investing','Tax','Retirement','Other']],['id'=>'message','type'=>'textarea','label'=>'What do you need help with?','required'=>true]]);
    $add('agency-onboarding','Agency','New Client Onboarding','Agency client onboarding questionnaire.',[['id'=>'name','type'=>'text','label'=>'Contact name','required'=>true],['id'=>'email','type'=>'email','label'=>'Email','required'=>true],['id'=>'company','type'=>'text','label'=>'Company','required'=>true],['id'=>'services','type'=>'checkboxes','label'=>'Services needed','required'=>true,'options'=>['Branding','Website','SEO','Ads','Content']],['id'=>'goals','type'=>'textarea','label'=>'Goals','required'=>true]]);
    $add('project-brief','Agency','Project Brief','Collect project requirements.',[['id'=>'name','type'=>'text','label'=>'Name','required'=>true],['id'=>'email','type'=>'email','label'=>'Email','required'=>true],['id'=>'project','type'=>'text','label'=>'Project name','required'=>true],['id'=>'deadline','type'=>'date','label'=>'Desired deadline','required'=>false],['id'=>'brief','type'=>'textarea','label'=>'Project brief','required'=>true]]);
    $add('demo-feedback','Feedback','Demo Feedback','Follow-up after a demo.',[['id'=>'email','type'=>'email','label'=>'Email','required'=>true],['id'=>'score','type'=>'rating','label'=>'How useful was the demo?','required'=>true],['id'=>'next','type'=>'select','label'=>'Next step','required'=>true,'options'=>['Talk to sales','Start trial','Need more information','Not now']],['id'=>'notes','type'=>'textarea','label'=>'Notes','required'=>false]]);
    $add('newsletter','Marketing','Newsletter Signup','Simple newsletter opt-in.',[['id'=>'email','type'=>'email','label'=>'Email address','required'=>true],['id'=>'name','type'=>'text','label'=>'First name','required'=>false]]);
    $add('waitlist','Marketing','Waitlist','Product waitlist.',[['id'=>'email','type'=>'email','label'=>'Email','required'=>true],['id'=>'name','type'=>'text','label'=>'Name','required'=>false],['id'=>'use_case','type'=>'textarea','label'=>'What will you use it for?','required'=>false]]);
    $add('beta-application','Product','Beta Application','Beta tester application.',[['id'=>'name','type'=>'text','label'=>'Name','required'=>true],['id'=>'email','type'=>'email','label'=>'Email','required'=>true],['id'=>'role','type'=>'text','label'=>'Role','required'=>true],['id'=>'why','type'=>'textarea','label'=>'Why do you want to join?','required'=>true]]);
    $add('podcast-guest','Content','Podcast Guest Application','Guest intake.',[['id'=>'name','type'=>'text','label'=>'Name','required'=>true],['id'=>'email','type'=>'email','label'=>'Email','required'=>true],['id'=>'topic','type'=>'text','label'=>'Proposed topic','required'=>true],['id'=>'bio','type'=>'textarea','label'=>'Short bio','required'=>true]]);
    $add('speaking-request','Content','Speaking Request','Speaker inquiry.',[['id'=>'name','type'=>'text','label'=>'Name','required'=>true],['id'=>'email','type'=>'email','label'=>'Email','required'=>true],['id'=>'event','type'=>'text','label'=>'Event','required'=>true],['id'=>'date','type'=>'date','label'=>'Event date','required'=>true],['id'=>'details','type'=>'textarea','label'=>'Event details','required'=>true]]);
    $add('partnership','Business','Partnership Inquiry','Business partnership intake.',[['id'=>'name','type'=>'text','label'=>'Name','required'=>true],['id'=>'email','type'=>'email','label'=>'Work email','required'=>true],['id'=>'company','type'=>'text','label'=>'Company','required'=>true],['id'=>'proposal','type'=>'textarea','label'=>'Partnership proposal','required'=>true]]);
    $add('vendor','Business','Vendor Application','Vendor intake.',[['id'=>'company','type'=>'text','label'=>'Company','required'=>true],['id'=>'email','type'=>'email','label'=>'Email','required'=>true],['id'=>'category','type'=>'select','label'=>'Category','required'=>true,'options'=>['Technology','Marketing','Operations','Finance','Other']],['id'=>'details','type'=>'textarea','label'=>'Tell us about your offering','required'=>true]]);
    $add('booking-request','Scheduling','Booking Request','Simple appointment request.',[['id'=>'name','type'=>'text','label'=>'Name','required'=>true],['id'=>'email','type'=>'email','label'=>'Email','required'=>true],['id'=>'date','type'=>'date','label'=>'Preferred date','required'=>true],['id'=>'time','type'=>'time','label'=>'Preferred time','required'=>true],['id'=>'notes','type'=>'textarea','label'=>'Notes','required'=>false]]);
    $add('one-on-one','Scheduling','One-on-One Meeting','Calendly-style one-on-one intake.',[['id'=>'name','type'=>'text','label'=>'Name','required'=>true],['id'=>'email','type'=>'email','label'=>'Email','required'=>true],['id'=>'topic','type'=>'select','label'=>'Meeting topic','required'=>true,'options'=>['Intro','Demo','Consultation','Support']],['id'=>'notes','type'=>'textarea','label'=>'Anything we should know?','required'=>false]]);
    $add('group-meeting','Scheduling','Group Meeting Registration','Group session registration.',[['id'=>'name','type'=>'text','label'=>'Name','required'=>true],['id'=>'email','type'=>'email','label'=>'Email','required'=>true],['id'=>'company','type'=>'text','label'=>'Company','required'=>false],['id'=>'questions','type'=>'textarea','label'=>'Questions','required'=>false]]);
    $add('team-meeting','Scheduling','Team Meeting Request','Request a meeting with multiple people.',[['id'=>'name','type'=>'text','label'=>'Name','required'=>true],['id'=>'email','type'=>'email','label'=>'Email','required'=>true],['id'=>'department','type'=>'select','label'=>'Team','required'=>true,'options'=>['Sales','Support','Success','Engineering']],['id'=>'agenda','type'=>'textarea','label'=>'Agenda','required'=>true]]);
    $add('office-hours','Education','Office Hours','Student or customer office-hours intake.',[['id'=>'name','type'=>'text','label'=>'Name','required'=>true],['id'=>'email','type'=>'email','label'=>'Email','required'=>true],['id'=>'topic','type'=>'text','label'=>'Topic','required'=>true],['id'=>'question','type'=>'textarea','label'=>'Question','required'=>true]]);
    $add('mentor-session','Education','Mentor Session','Mentoring request.',[['id'=>'name','type'=>'text','label'=>'Name','required'=>true],['id'=>'email','type'=>'email','label'=>'Email','required'=>true],['id'=>'goal','type'=>'textarea','label'=>'What would you like to work on?','required'=>true],['id'=>'level','type'=>'select','label'=>'Level','required'=>true,'options'=>['Beginner','Intermediate','Advanced']]]);
    $add('donation-inquiry','Nonprofit','Donation Inquiry','Nonprofit donor inquiry.',[['id'=>'name','type'=>'text','label'=>'Name','required'=>true],['id'=>'email','type'=>'email','label'=>'Email','required'=>true],['id'=>'interest','type'=>'select','label'=>'Area of interest','required'=>true,'options'=>['Donate','Volunteer','Partner','Sponsor']],['id'=>'message','type'=>'textarea','label'=>'Message','required'=>false]]);
    $add('volunteer','Nonprofit','Volunteer Application','Volunteer intake.',[['id'=>'name','type'=>'text','label'=>'Name','required'=>true],['id'=>'email','type'=>'email','label'=>'Email','required'=>true],['id'=>'skills','type'=>'textarea','label'=>'Skills / experience','required'=>true],['id'=>'availability','type'=>'text','label'=>'Availability','required'=>true]]);
    $add('restaurant-reservation','Hospitality','Restaurant Reservation Request','Reservation inquiry.',[['id'=>'name','type'=>'text','label'=>'Name','required'=>true],['id'=>'email','type'=>'email','label'=>'Email','required'=>true],['id'=>'date','type'=>'date','label'=>'Date','required'=>true],['id'=>'time','type'=>'time','label'=>'Time','required'=>true],['id'=>'guests','type'=>'number','label'=>'Guests','required'=>true],['id'=>'notes','type'=>'textarea','label'=>'Notes','required'=>false]]);
    $add('photo-session','Creative','Photography Session','Photography inquiry.',[['id'=>'name','type'=>'text','label'=>'Name','required'=>true],['id'=>'email','type'=>'email','label'=>'Email','required'=>true],['id'=>'session','type'=>'select','label'=>'Session type','required'=>true,'options'=>['Portrait','Family','Wedding','Product','Other']],['id'=>'date','type'=>'date','label'=>'Preferred date','required'=>false]]);
    $add('design-brief','Creative','Design Brief','Creative project intake.',[['id'=>'name','type'=>'text','label'=>'Name','required'=>true],['id'=>'email','type'=>'email','label'=>'Email','required'=>true],['id'=>'project','type'=>'text','label'=>'Project','required'=>true],['id'=>'style','type'=>'textarea','label'=>'Style / references','required'=>true],['id'=>'budget','type'=>'select','label'=>'Budget','required'=>false,'options'=>['<$1k','$1k-$5k','$5k-$10k','$10k+']]]);
    // Multi-step starter templates. Each includes real Page Break fields so installation creates a working wizard.
        $add('job-application-multistep','Hiring','Job Application — 3 Steps','A professional application wizard for candidate details, experience, repeatable work and education history, resume upload, and consent.',[['id'=>'applicant_name','type'=>'name','label'=>'Full Name','required'=>true],['id'=>'applicant_email','type'=>'email','label'=>'Email Address','required'=>true],['id'=>'applicant_phone','type'=>'phone','label'=>'Phone Number','required'=>true],['id'=>'pb_professional','type'=>'page_break','label'=>'Professional Background','required'=>false,'step_title'=>'Professional Background','step_description'=>'Tell us about your experience, education, and the role you are applying for.'],['id'=>'position','type'=>'select','label'=>'Position Applied For','required'=>true,'options'=>['Sales','Engineering','Marketing','Operations','Customer Support','Other']],['id'=>'work_history','type'=>'repeater','label'=>'Work Experience','required'=>false,'min_items'=>1,'max_items'=>10,'default_items'=>1,'item_label'=>'Work Experience','add_text'=>'Add Another Employer','remove_text'=>'Remove Employer','child_fields'=>[['id'=>'company','type'=>'text','label'=>'Company Name','required'=>true],['id'=>'job_title','type'=>'text','label'=>'Job Title','required'=>true],['id'=>'start_date','type'=>'date','label'=>'Start Date','required'=>true],['id'=>'end_date','type'=>'date','label'=>'End Date','required'=>false],['id'=>'responsibilities','type'=>'textarea','label'=>'Responsibilities','required'=>false]]],['id'=>'education_history','type'=>'repeater','label'=>'Education History','required'=>false,'min_items'=>1,'max_items'=>10,'default_items'=>1,'item_label'=>'Education','add_text'=>'Add Another Institution','remove_text'=>'Remove Education','child_fields'=>[['id'=>'institution','type'=>'text','label'=>'College / University','required'=>true],['id'=>'degree','type'=>'text','label'=>'Degree / Qualification','required'=>true],['id'=>'field_of_study','type'=>'text','label'=>'Field of Study','required'=>false],['id'=>'edu_start','type'=>'date','label'=>'Start Date','required'=>false],['id'=>'edu_end','type'=>'date','label'=>'End Date','required'=>false]]],['id'=>'portfolio','type'=>'url','label'=>'Portfolio / LinkedIn URL','required'=>false],['id'=>'pb_documents','type'=>'page_break','label'=>'Documents & Final Details','required'=>false,'step_title'=>'Documents & Final Details','step_description'=>'Upload your resume and provide any final information.'],['id'=>'resume','type'=>'file','label'=>'Resume / CV','required'=>true],['id'=>'cover_letter','type'=>'textarea','label'=>'Cover Letter','required'=>false],['id'=>'start_date_available','type'=>'date','label'=>'Available Start Date','required'=>false],['id'=>'consent','type'=>'terms','label'=>'I agree to the processing of my application data.','required'=>true],['id'=>'submit','type'=>'submit','label'=>'Submit Application','required'=>false]]);

    $add('client-intake-multistep','Professional','Client Intake — 4 Steps','A structured new-client onboarding form covering contact details, project needs, timeline, and confirmation.',[['id'=>'client_name','type'=>'name','label'=>'Full Name','required'=>true],['id'=>'client_email','type'=>'email','label'=>'Email Address','required'=>true],['id'=>'client_phone','type'=>'phone','label'=>'Phone Number','required'=>false],['id'=>'pb_needs','type'=>'page_break','label'=>'Project Needs','required'=>false,'step_title'=>'Project Needs','step_description'=>'Help us understand what you need and what success looks like.'],['id'=>'service','type'=>'select','label'=>'Service Needed','required'=>true,'options'=>['Consulting','Website','Marketing','Automation','Design','Other']],['id'=>'goals','type'=>'textarea','label'=>'Primary Goals','required'=>true],['id'=>'scope','type'=>'textarea','label'=>'Project Scope / Requirements','required'=>false],['id'=>'pb_timeline','type'=>'page_break','label'=>'Timeline & Budget','required'=>false,'step_title'=>'Timeline & Budget','step_description'=>'Share your target timeline and investment range.'],['id'=>'deadline','type'=>'date','label'=>'Desired Start / Deadline','required'=>false],['id'=>'budget','type'=>'select','label'=>'Budget Range','required'=>false,'options'=>['Under $1,000','$1,000–$5,000','$5,000–$10,000','$10,000–$25,000','$25,000+']],['id'=>'pb_confirmation','type'=>'page_break','label'=>'Confirmation','required'=>false,'step_title'=>'Confirmation','step_description'=>'Review your information and confirm you are ready to submit.'],['id'=>'notes','type'=>'textarea','label'=>'Additional Notes','required'=>false],['id'=>'consent','type'=>'terms','label'=>'I confirm the information provided is accurate.','required'=>true],['id'=>'submit','type'=>'submit','label'=>'Submit Intake','required'=>false]]);

    $add('event-registration-multistep','Events','Event Registration — 3 Steps','A multi-step attendee registration form with ticket selection, preferences, and consent.',[['id'=>'attendee_name','type'=>'name','label'=>'Attendee Name','required'=>true],['id'=>'attendee_email','type'=>'email','label'=>'Email Address','required'=>true],['id'=>'attendee_phone','type'=>'phone','label'=>'Phone Number','required'=>false],['id'=>'pb_ticket','type'=>'page_break','label'=>'Registration Details','required'=>false,'step_title'=>'Registration Details','step_description'=>'Choose your registration type and attendance preferences.'],['id'=>'ticket','type'=>'select','label'=>'Registration Type','required'=>true,'options'=>['General Admission','VIP','Speaker','Sponsor','Student']],['id'=>'attendance','type'=>'radio','label'=>'Attendance','required'=>true,'options'=>['In Person','Virtual']],['id'=>'sessions','type'=>'checkbox','label'=>'Sessions of Interest','required'=>false,'options'=>['Opening Keynote','Workshop A','Workshop B','Networking','Closing Session']],['id'=>'pb_preferences','type'=>'page_break','label'=>'Preferences & Consent','required'=>false,'step_title'=>'Preferences & Consent','step_description'=>'Add accessibility or dietary requirements and confirm your registration.'],['id'=>'diet','type'=>'text','label'=>'Dietary Requirements','required'=>false],['id'=>'accessibility','type'=>'textarea','label'=>'Accessibility Requirements','required'=>false],['id'=>'consent','type'=>'terms','label'=>'I agree to the event terms and privacy policy.','required'=>true],['id'=>'submit','type'=>'submit','label'=>'Complete Registration','required'=>false]]);

    $add('employee-onboarding-multistep','HR','New Employee Onboarding — 4 Steps','Collect new-hire information, employment details, emergency contact information, and required acknowledgements.',[['id'=>'employee_name','type'=>'name','label'=>'Legal Full Name','required'=>true],['id'=>'employee_email','type'=>'email','label'=>'Personal Email','required'=>true],['id'=>'employee_phone','type'=>'phone','label'=>'Phone Number','required'=>true],['id'=>'employee_address','type'=>'address','label'=>'Home Address','required'=>true],['id'=>'pb_employment','type'=>'page_break','label'=>'Employment Details','required'=>false,'step_title'=>'Employment Details','step_description'=>'Confirm your role, start date, and work preferences.'],['id'=>'role','type'=>'text','label'=>'Job Title','required'=>true],['id'=>'department','type'=>'select','label'=>'Department','required'=>true,'options'=>['Sales','Engineering','Marketing','Operations','Finance','HR','Other']],['id'=>'start_date','type'=>'date','label'=>'Start Date','required'=>true],['id'=>'work_mode','type'=>'radio','label'=>'Work Arrangement','required'=>true,'options'=>['On-site','Hybrid','Remote']],['id'=>'pb_emergency','type'=>'page_break','label'=>'Emergency Contact','required'=>false,'step_title'=>'Emergency Contact','step_description'=>'Provide someone we can contact in an emergency.'],['id'=>'emergency_name','type'=>'text','label'=>'Emergency Contact Name','required'=>true],['id'=>'emergency_phone','type'=>'phone','label'=>'Emergency Contact Phone','required'=>true],['id'=>'relationship','type'=>'text','label'=>'Relationship','required'=>true],['id'=>'pb_documents','type'=>'page_break','label'=>'Documents & Confirmation','required'=>false,'step_title'=>'Documents & Confirmation','step_description'=>'Upload required documents and acknowledge the onboarding information.'],['id'=>'id_document','type'=>'file','label'=>'Identity / Required Document','required'=>false],['id'=>'notes','type'=>'textarea','label'=>'Additional Information','required'=>false],['id'=>'consent','type'=>'terms','label'=>'I confirm the information provided is accurate.','required'=>true],['id'=>'submit','type'=>'submit','label'=>'Complete Onboarding','required'=>false]]);

    $add('course-registration-multistep','Education','Course Registration — 3 Steps','A course or workshop enrollment wizard with learner details, course selection, and final confirmation.',[['id'=>'student_name','type'=>'name','label'=>'Student Name','required'=>true],['id'=>'student_email','type'=>'email','label'=>'Email Address','required'=>true],['id'=>'student_phone','type'=>'phone','label'=>'Phone Number','required'=>false],['id'=>'pb_course','type'=>'page_break','label'=>'Course Selection','required'=>false,'step_title'=>'Course Selection','step_description'=>'Choose the course, level, and preferred schedule.'],['id'=>'course','type'=>'select','label'=>'Course','required'=>true,'options'=>['Beginner','Intermediate','Advanced','Professional Certificate']],['id'=>'format','type'=>'radio','label'=>'Learning Format','required'=>true,'options'=>['Online','In Person','Hybrid']],['id'=>'schedule','type'=>'select','label'=>'Preferred Schedule','required'=>true,'options'=>['Weekday Morning','Weekday Evening','Saturday','Flexible']],['id'=>'pb_background','type'=>'page_break','label'=>'Background & Confirmation','required'=>false,'step_title'=>'Background & Confirmation','step_description'=>'Tell us about your experience and confirm your registration.'],['id'=>'experience','type'=>'textarea','label'=>'Relevant Experience','required'=>false],['id'=>'goals','type'=>'textarea','label'=>'What do you want to achieve?','required'=>true],['id'=>'accessibility','type'=>'textarea','label'=>'Accessibility / Learning Requirements','required'=>false],['id'=>'consent','type'=>'terms','label'=>'I agree to the course terms and privacy policy.','required'=>true],['id'=>'submit','type'=>'submit','label'=>'Register for Course','required'=>false]]);

    $add('service-booking-multistep','Booking','Service Booking — 3 Steps','A service inquiry and appointment wizard designed to work with FormPilot scheduling and calendar integrations.',[['id'=>'customer_name','type'=>'name','label'=>'Full Name','required'=>true],['id'=>'customer_email','type'=>'email','label'=>'Email Address','required'=>true],['id'=>'customer_phone','type'=>'phone','label'=>'Phone Number','required'=>true],['id'=>'pb_service','type'=>'page_break','label'=>'Choose Service','required'=>false,'step_title'=>'Choose Service','step_description'=>'Select the service and tell us what you need.'],['id'=>'service','type'=>'select','label'=>'Service','required'=>true,'options'=>['Consultation','Installation','Support','Training','Other']],['id'=>'details','type'=>'textarea','label'=>'What do you need help with?','required'=>true],['id'=>'timezone','type'=>'timezone','label'=>'Timezone','required'=>true],['id'=>'pb_schedule','type'=>'page_break','label'=>'Schedule & Confirmation','required'=>false,'step_title'=>'Schedule & Confirmation','step_description'=>'Choose an available appointment and confirm your details.'],['id'=>'appointment','type'=>'booking','label'=>'Appointment Date & Time','required'=>true],['id'=>'notes','type'=>'textarea','label'=>'Additional Notes','required'=>false],['id'=>'consent','type'=>'terms','label'=>'I agree to the booking and privacy terms.','required'=>true],['id'=>'submit','type'=>'submit','label'=>'Book Appointment','required'=>false]]);

    return $t;
}

function ssb_templates_page(){
    if(!current_user_can('manage_options')) return;
    if(!ssb_is_paid()){
        echo '<div class="wrap fp-product-admin"><div class="fp-upgrade-panel"><span class="fp-card-kicker">FORMPILOT PRO</span><h1>Form Templates are a Pro feature</h1><p>The free plan lets you build up to 3 forms from scratch. Pro gives you the complete ready-made Form Template library, so you can start from a professional form and customize it.</p><p><a class="button button-primary button-large" href="'.esc_url(admin_url('admin.php?page=ssb-license')).'">Activate Pro License</a> <a class="button button-large" href="'.esc_url(admin_url('admin.php?page=ssb-forms')).'">Back to Forms</a></p></div></div>';
        return;
    }

    $templates=ssb_template_library();
    $cat=sanitize_text_field($_GET['cat']??'');
    if(isset($_POST['ssb_template_use']) && check_admin_referer('ssb_template_use')){
        $id=sanitize_key($_POST['ssb_template_use']); $tpl=$templates[$id]??null;
        if($tpl){
            global $wpdb;
            $fields=$tpl['fields'];
            $settings=['notify_email'=>get_option('admin_email'),'success_msg'=>'Thanks! We received your request.','submit_label'=>'Submit','display_title'=>$tpl['name'],'show_title'=>true,'show_description'=>true,'show_labels'=>true,'send_copy'=>false,'email_subject'=>$tpl['name'],'redirect_url'=>'','primary_color'=>'#6366f1','btn_radius'=>10,'integrations'=>['stripe'=>['enabled'=>false,'amount'=>0,'currency'=>'USD','description'=>''],'google_calendar'=>['enabled'=>false,'calendar_id'=>'primary','event_label'=>'','brand_name'=>'']], 'style'=>[],'multistep_enabled'=>false,'multistep_progress'=>'both','multistep_next_label'=>'Next','multistep_prev_label'=>'Previous','multistep_submit_label'=>'Submit'];
            $has_page_break=false; foreach($fields as $tf){ if(($tf['type']??'')==='page_break'){ $has_page_break=true; break; } }
            if($has_page_break){ $settings['multistep_enabled']=true; }
            $wpdb->insert($wpdb->prefix.'ssb_forms',['form_name'=>$tpl['name'],'form_slug'=>ssb_unique_slug($tpl['name'],0),'description'=>$tpl['description'],'fields'=>wp_json_encode($fields),'settings'=>wp_json_encode($settings),'status'=>'active']);
            echo '<div class="notice notice-success is-dismissible"><p><strong>Template installed.</strong> <a href="'.esc_url(admin_url('admin.php?page=ssb-forms')).'">Open Form Builder</a></p></div>';
        }
    }
    $cats=array_unique(array_map(fn($x)=>$x['category'],$templates));
    echo '<div class="wrap fp-product-admin">';
    echo '<div class="fp-product-hero"><div><div class="fp-product-kicker">FORMPILOT PRO · FORM LIBRARY</div><h1>Form Templates</h1><p>Choose a professionally structured starting point, install it as a real FormPilot form, then customize it in the Form Builder.</p></div><div class="fp-license-pill is-active">'.count($templates).' templates</div></div>';
    echo '<div style="margin:18px 0;padding:15px 18px;background:#fff;border:1px solid #e5e7eb;border-radius:14px;display:flex;gap:10px;align-items:center;flex-wrap:wrap;"><strong>Browse by category:</strong><a class="button '.(!$cat?'button-primary':'').'" href="'.esc_url(admin_url('admin.php?page=ssb-templates')).'">All templates</a>';
    foreach($cats as $c) echo '<a class="button '.($cat===$c?'button-primary':'').'" href="'.esc_url(add_query_arg(['page'=>'ssb-templates','cat'=>$c],admin_url('admin.php'))).'">'.esc_html($c).'</a>';
    echo '</div>';
    echo '<div class="fp-hub-grid" style="grid-template-columns:repeat(auto-fit,minmax(280px,1fr));">';
    foreach($templates as $tpl){
        if($cat&&$tpl['category']!==$cat) continue;
        $field_labels=array_slice(array_map(fn($f)=>$f['label']??ucfirst($f['id']??'Field'),$tpl['fields']),0,4);
        $template_is_multistep=false; $template_steps=1; foreach($tpl['fields'] as $tf){ if(($tf['type']??'')==='page_break'){ $template_is_multistep=true; $template_steps++; } }
        echo '<div class="fp-hub-card" style="display:block;text-decoration:none;">';
        echo '<div style="display:flex;justify-content:space-between;gap:10px;align-items:flex-start;"><span class="fp-card-kicker">'.esc_html($tpl['category']).'</span><span style="background:#eef2ff;color:#4338ca;padding:5px 9px;border-radius:999px;font-size:10px;font-weight:800;letter-spacing:.04em;">PRO</span></div>';
        echo '<h2 style="margin:7px 0 5px;font-size:19px;">'.esc_html($tpl['name']).'</h2><p style="color:#64748b;min-height:42px;margin:0 0 12px;">'.esc_html($tpl['description']).'</p>';
        echo '<div style="display:flex;flex-wrap:wrap;gap:6px;margin-bottom:15px;">'; foreach($field_labels as $label) echo '<span style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:999px;padding:5px 8px;font-size:11px;color:#475569;">'.esc_html($label).'</span>'; if(count($tpl['fields'])>4) echo '<span style="padding:5px 4px;font-size:11px;color:#64748b;">+'.(count($tpl['fields'])-4).' more</span>'; echo '</div>';
        echo '<div style="display:flex;justify-content:space-between;align-items:center;gap:10px;flex-wrap:wrap;"><div><small style="color:#64748b;">'.count($tpl['fields']).' fields</small>'.($template_is_multistep ? ' <span style="background:#ecfdf5;color:#047857;padding:4px 8px;border-radius:999px;font-size:10px;font-weight:800;">MULTI-STEP · '.$template_steps.' STEPS</span>' : '').'</div><form method="post">'.wp_nonce_field('ssb_template_use','_wpnonce',true,false).'<input type="hidden" name="ssb_template_use" value="'.esc_attr($tpl['id']).'"><button class="button button-primary">Use template</button></form></div>';
        echo '</div>';
    }
    echo '</div></div>';
}
